// <auto-generated />
using System;
using Balay_Balay_Resort.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Balay_Balay_Resort.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260507114809_AddIsActiveToProperty")]
    partial class AddIsActiveToProperty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Balay_Balay_Resort.Models.Amenity", b =>
                {
                    b.Property<int>("Amenity_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Amenity_ID"));

                    b.Property<string>("Amenity_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Amenity_ID");

                    b.ToTable("Amenities");
                });

            modelBuilder.Entity("Balay_Balay_Resort.Models.Amenity_Property", b =>
                {
                    b.Property<int>("PropertyAmenity_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyAmenity_ID"));

                    b.Property<int>("Amenity_ID")
                        .HasColumnType("int");

                    b.Property<int>("Property_ID")
                        .HasColumnType("int");

                    b.HasKey("PropertyAmenity_ID");

                    b.HasIndex("Amenity_ID");

                    b.HasIndex("Property_ID");

                    b.ToTable("Amenities_Properties");
                });

            modelBuilder.Entity("Balay_Balay_Resort.Models.Booking", b =>
                {
                    b.Property<int>("Booking_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Booking_ID"));

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfGuest")
                        .HasColumnType("int");

                    b.Property<int>("Property_ID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("User_ID")
                        .HasColumnType("int");

                    b.HasKey("Booking_ID");

                    b.HasIndex("Property_ID");

                    b.HasIndex("User_ID");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Balay_Balay_Resort.Models.Feedback", b =>
                {
                    b.Property<int>("Feedback_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Feedback_ID"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Property_ID")
                        .HasColumnType("int");

                    b.Property<decimal>("ReviewRate")
                        .HasColumnType("decimal(3,1)");

                    b.Property<int>("User_ID")
                        .HasColumnType("int");

                    b.HasKey("Feedback_ID");

                    b.HasIndex("Property_ID");

                    b.HasIndex("User_ID");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("Balay_Balay_Resort.Models.Property", b =>
                {
                    b.Property<int>("Property_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Property_ID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AmountUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BathNum")
                        .HasColumnType("int");

                    b.Property<int>("BedNum")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GuestCapacity")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PropertyImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnitNumber")
                        .HasColumnType("int");

                    b.HasKey("Property_ID");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("Balay_Balay_Resort.Models.Transaction", b =>
                {
                    b.Property<int>("Transaction_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Transaction_ID"));

                    b.Property<int>("Booking_ID")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Transaction_ID");

                    b.HasIndex("Booking_ID")
                        .IsUnique();

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Balay_Balay_Resort.Models.User", b =>
                {
                    b.Property<int>("User_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Balay_Balay_Resort.Models.Amenity_Property", b =>
                {
                    b.HasOne("Balay_Balay_Resort.Models.Amenity", "Amenity")
                        .WithMany("Amenity_Properties")
                        .HasForeignKey("Amenity_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Balay_Balay_Resort.Models.Property", "Property")
                        .WithMany("Amenity_Properties")
                        .HasForeignKey("Property_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenity");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Balay_Balay_Resort.Models.Booking", b =>
                {
                    b.HasOne("Balay_Balay_Resort.Models.Property", "Property")
                        .WithMany("Bookings")
                        .HasForeignKey("Property_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Balay_Balay_Resort.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Balay_Balay_Resort.Models.Feedback", b =>
                {
                    b.HasOne("Balay_Balay_Resort.Models.Property", "Property")
                        .WithMany("Feedbacks")
                        .HasForeignKey("Property_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Balay_Balay_Resort.Models.User", "User")
                        .WithMany("Feedbacks")
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Balay_Balay_Resort.Models.Transaction", b =>
                {
                    b.HasOne("Balay_Balay_Resort.Models.Booking", "Booking")
                        .WithOne("Transaction")
                        .HasForeignKey("Balay_Balay_Resort.Models.Transaction", "Booking_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Balay_Balay_Resort.Models.Amenity", b =>
                {
                    b.Navigation("Amenity_Properties");
                });

            modelBuilder.Entity("Balay_Balay_Resort.Models.Booking", b =>
                {
                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Balay_Balay_Resort.Models.Property", b =>
                {
                    b.Navigation("Amenity_Properties");

                    b.Navigation("Bookings");

                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("Balay_Balay_Resort.Models.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Feedbacks");
                });
#pragma warning restore 612, 618
        }
    }
}
